---
title: "SVM"
output: pdf_document
date: "2024-03-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load data
```{r}
load("/Users/zhanghantao/Desktop/ST340 Programming for DS/mnist.tiny.RData")
train.X=train.X/255 
test.X=test.X/255
```

#### Visualize data
```{r}
library(grid)
grid.newpage()
grid.raster(array(aperm(array(train.X[1:50,], c(5,10,28,28)), c(4,1,3,2)), c(140,280)), interpolate=FALSE)
```

#### Try different kernels and evaluate their accuracy
```{r}
library(e1071)
dat = data.frame(train.X, y = as.factor(train.labels))
linearModel = svm(y ~ ., data = dat, kernel = "linear", cross = 3, scale = FALSE)
polyModel = svm(y ~ ., data = dat, kernel = "polynomial", cross = 3, scale = FALSE)
rbfModel = svm(y ~ ., data = dat, kernel = "radial", cross = 3, scale = FALSE)
```

```{r}
eval_linear = predict(linearModel, newdata = test.X)
eval_poly = predict(polyModel, newdata = test.X)
eval_rbf = predict(rbfModel, newdata = test.X)
accuracy_linear = mean(eval_linear == as.factor(test.labels))
accuracy_poly = mean(eval_poly == as.factor(test.labels))
accuracy_rbf = mean(eval_rbf == as.factor(test.labels))
```


#### Grid search on the parameters of RBF kernel and find the optimal cost and gamma

```{r}
grid_search = function(log.C.range, log.gamma.range){
  max_accuracy = 0
  for(i in 1:length(log.C.range)){
    for(j in 1:length(log.gamma.range)){
      c = exp(log.C.range[i])
      g = exp(log.gamma.range[j])
      model = rbfModel = svm(y ~ ., data = dat, kernel = "radial", cross = 3, scale = FALSE, cost = c, gamma = g)
      if(model$tot.accuracy > max_accuracy){
        max_accuracy = model$tot.accuracy
        print(max_accuracy)
        optimal_c = c
        optimal_gamma = g
      }
    }
  }
  return(list(optimal_c, optimal_gamma))
}
```

```{r}
log.C.range = log(2:6)
log.gamma.range = log(0.001*(2:6))
grid_search(log.C.range, log.gamma.range)
```

#### Evaluate the SVM model with the optimal parameters
```{r}
optimal_model = svm(y ~ ., data = dat, kernel = "radial", scale = FALSE, cost = 4, gamma = 0.006)
eval_optimal = predict(optimal_model, newdata = test.X)
optimal_accuracy = mean(eval_optimal == as.factor(test.labels))
```

```{r}
grid.newpage()
grid.raster(array(aperm(array(test.X[1:50,], c(5,10,28,28)), c(4,1,3,2)), c(140,280)), interpolate=FALSE)
print(matrix(eval_optimal[1:50], nrow = 5, ncol = 10, byrow = FALSE))
```